blank_issues_enabled: false
contact_links:
  - name: 버그 신고
    url: https://github.com/ott-service/OTMeal/issues/new?template=bug_report.md
    about: 프로젝트에서 발생한 버그를 신고합니다.
  - name: 기능 요청
    url: https://github.com/ott-service/OTMeal/issues/new?template=feature_request.md
    about: 프로젝트에 필요한 새로운 기능을 제안합니다.
